### ISSUE TITLE
issue with hypersalad enthropy

### ISSUE THREAD

**Issue by ketchup0is0a0smoothie** [saladtheory/saladtheory.github.io#14]
Hi, I just tried to calculate enthropy of fries in order to find out how hyper-salady they are, and i have stumbled to few issues, which are following:
1) It seems that entrophy rises with scale, so the same type of salad identical ingredients density and type can have different number, so plate of 50 fries makes 5,5, but if we manage to put 5000 fries it will make twice as much. This alone makes this number not meaning anything if taken out of broader context
2) As I understand, dressing makes one ingredient, but what about salt? should i think of it as of ketchup, or should i count every single grain?
3) lets assume, that I made fries salad from two slightly different type of potatoes, at which point should i count them as a two unique ingredients?
4) what is enthropy of a "proper" salad? By "proper" of course I mean salad which is widely recognized as such. Depending on above questions, fries can make up to about i(e) equal to 30.

**Comment by gmalmquist** [comment]
1. correct. this is why that measure is defined logarithmically - adding more ingredients when you get to 5000 ingredients still increases entropy, but increasingly negligably.
2. this issue is complex enough that it would require its own in-depth analysis, and seems to relate closely to the [paradox of the heap](https://en.wikipedia.org/wiki/Sorites_paradox#Paradox_of_the_heap)
3. this requires more research :)
4. it depends quite a lot on the particular salad in question!

I will say with all of this - the entropy is probably most meaningful when considering low-entropy foods when are borderline between salads and low-entropy hypersalads.
